import MainReducer from './main';
import UserReducer from './user';
import ResumeReducer from './resume';
import BlogReducer from './blog';

export const reducers = {
  main: MainReducer,
  user: UserReducer,
  resume: ResumeReducer,
  blog: BlogReducer,
};

export {
  fetchMainData,
  fetchSettings,
  fetchAddSetting,
  fetchUpdateSetting,
  getMainData,
  getMainIsLoading,
  getMainIsError,
  getMainError,
  getMainSettings,
  getMainSettingsLoading,
  getMainSettingsError,
  getMainSettingsLoadingError,
} from './main';

export {
  loadUserData,
  updateUser,
  login,
  logout,
  register,
  clearUserError,
  fetchUserData,
  fetchUserUpdate,
  fetchUserLogin,
  fetchUserLogout,
  fetchUserRegister,
  fetchUserPasswordChange,
  getUserData,
  getUserToken,
  getUserLoggedin,
  /** Loading Functions **/
  getUserIsLoading,
  getUserIsError,
  getUserError,
  /** Updating Functions **/
  getUserIsUpdating,
  getUserIsUpdatingError,
  getUserUpdatingError,
  /** Login Functions **/
  getUserIsLoggingIn,
  getUserIsLoggingInError,
  getUserLoggingInError,
  /** Logout Functions **/
  getUserIsLoggingOut,
  getUserIsLoggingOutError,
  getUserLoggingOutError,
  /** Register Functions **/
  getUserIsRegistering,
  getUserIsRegisteringError,
  getUserRegisteringError,
  /** Password Change Functions **/
  getUserIsPasswordChanging,
  getUserIsPasswordChangingError,
  getUserPasswordChangingError,
} from './user';

export {
  /** Resume **/
  fetchGetAllResumes,
  fetchUpdateResume,
  fetchCreateResume,
  fetchDeleteResume,
  clearResumesError,
  clearAddResumeError,
  clearDeleteResumeError,
  clearUpdateResumeError,
  getResumes,
  getResumesLoading,
  getResumesHasError,
  getResumesError,
  getCreateResumeLoading,
  getCreateResumeHasError,
  getCreateResumeError,
  getUpdateResumeLoading,
  getUpdateResumeHasError,
  getUpdateResumeError,
  getDeleteResumeLoading,
  getDeleteResumeHasError,
  getDeleteResumeError,
  /** Work Experience **/
  fetchAddWorkExperience,
  fetchUpdateWorkExperience,
  fetchDeleteWorkExperience,
  fetchGetAllWorkExperiences,
  clearWorkExperiencesError,
  clearAddWorkExperienceError,
  clearDeleteWorkExperienceError,
  clearUpdateWorkExperienceError,
  getWorkExperiences,
  getWorkExperiencesLoading,
  getWorkExperiencesHasError,
  getWorkExperiencesError,
  getCreateWorkExperienceLoading,
  getCreateWorkExperienceHasError,
  getCreateWorkExperienceError,
  getUpdateWorkExperienceLoading,
  getUpdateWorkExperienceHasError,
  getUpdateWorkExperienceError,
  getDeleteWorkExperienceLoading,
  getDeleteWorkExperienceHasError,
  getDeleteWorkExperienceError,
  /** Education **/
  fetchAddEducation,
  fetchUpdateEducation,
  fetchDeleteEducation,
  fetchGetAllEducations,
  clearEducationsError,
  clearAddEducationError,
  clearDeleteEducationError,
  clearUpdateEducationError,
  getEducations,
  getEducationsLoading,
  getEducationsHasError,
  getEducationsError,
  getCreateEducationLoading,
  getCreateEducationHasError,
  getCreateEducationError,
  getUpdateEducationLoading,
  getUpdateEducationHasError,
  getUpdateEducationError,
  getDeleteEducationLoading,
  getDeleteEducationHasError,
  getDeleteEducationError,
  /** Skills **/
  fetchAddSkill,
  fetchUpdateSkill,
  fetchDeleteSkill,
  fetchGetAllSkills,
  clearSkillsError,
  clearAddSkillError,
  clearDeleteSkillError,
  clearUpdateSkillError,
  getSkills,
  getSkillsLoading,
  getSkillsHasError,
  getSkillsError,
  getCreateSkillLoading,
  getCreateSkillHasError,
  getCreateSkillError,
  getUpdateSkillLoading,
  getUpdateSkillHasError,
  getUpdateSkillError,
  getDeleteSkillLoading,
  getDeleteSkillHasError,
  getDeleteSkillError,
} from './resume';

export {
  fetchMyBlogPosts,
  fetchBlogPosts,
  fetchBlogPost,
  fetchCreateBlogPost,
  fetchUpdateBlogPost,
  fetchDeleteBlogPost,
  blogReset,
  getPublicBlogPosts,
  getMyBlogPosts,
  getBlogPost,
  getMyBlogPostsLoading,
  getBlogPostsLoading,
  getBlogPostLoading,
  getBlogPostsError,
  getCreateBlogPostLoading,
  getCreateBlogPostError,
  getUpdateBlogPostLoading,
  getUpdateBlogPostError,
  getDeleteBlogPostLoading,
  getDeleteBlogPostError,
} from './blog';